window.uruworkCompanies = [
  {
    id: "el-palacio-del-cafe",
    name: "El Palacio del Cafe",
    category: "Gastronomia y hoteleria",
    area: "",
    roles: "Atencion, ventas, deposito y cafeteria.",
    applyUrl: "https://elpalaciodelcafe.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://elpalaciodelcafe.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "confiteria-carrera",
    name: "Confiteria Carrera",
    category: "Gastronomia y hoteleria",
    area: "Cordon.",
    roles: "Atencion, caja, cocina y elaboracion.",
    applyUrl: "https://carrera.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://carrera.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "carbonada-restaurant",
    name: "Carbonada Restaurant",
    category: "Gastronomia y hoteleria",
    area: "Pocitos.",
    roles: "Cocina, salon y atencion.",
    applyUrl: "https://carbonada.com.uy/",
    applyEmail: "",
    sourceUrl: "https://carbonada.com.uy/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "francis-restaurant",
    name: "Francis Restaurant",
    category: "Gastronomia y hoteleria",
    area: "Punta Carretas.",
    roles: "Cocina, mozos y atencion.",
    applyUrl: "https://francis.com.uy/",
    applyEmail: "",
    sourceUrl: "https://francis.com.uy/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "rodelu",
    name: "Rodelu",
    category: "Gastronomia y hoteleria",
    area: "Pocitos, Parque Rodo y otras sucursales.",
    roles: "Cocina, mostrador, reparto y salon.",
    applyUrl: "https://www.rodelu.com.uy/trabajo",
    applyEmail: "",
    sourceUrl: "https://www.rodelu.com.uy/trabajo",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "emporio",
    name: "Emporio",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Confiteria, panaderia, cocina, caja, mozos y deposito.",
    applyUrl: "https://emporio.com.uy/pages/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://emporio.com.uy/pages/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "la-pasiva",
    name: "La Pasiva",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Cocina, atencion, reparto, administracion y limpieza.",
    applyUrl: "https://www.lapasiva.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.lapasiva.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "mcdonalds-uruguay",
    name: "McDonald's Uruguay",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Atencion, cocina y primer empleo.",
    applyUrl: "https://www.mcdonalds.com.uy/trabaja-con-nosotros/postularme",
    applyEmail: "",
    sourceUrl: "https://www.mcdonalds.com.uy/trabaja-con-nosotros/postularme",
    verifiedAt: "2026-07-22",
    status: "Por revisar",
    active: true
  },
  {
    id: "hotel-montevideo",
    name: "Hotel Montevideo",
    category: "Gastronomia y hoteleria",
    area: "Pocitos.",
    roles: "Gastronomia, hoteleria y atencion.",
    applyUrl: "",
    applyEmail: "jobs@tay-group.com",
    sourceUrl: "https://hotelmvd.com/es/trabaja-con-nosotros.php",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "cala-di-volpe",
    name: "Cala di Volpe Boutique Hotel",
    category: "Gastronomia y hoteleria",
    area: "Punta Carretas.",
    roles: "Gastronomia, limpieza, recepcion y hoteleria.",
    applyUrl: "https://www.hotelcaladivolpe.com.uy/es/envio-de-cv",
    applyEmail: "",
    sourceUrl: "https://www.hotelcaladivolpe.com.uy/es/envio-de-cv",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "regency-hotels",
    name: "Regency Hotels",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Alimentos y bebidas, eventos, limpieza, recepcion y mantenimiento.",
    applyUrl: "https://www.regency.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://www.regency.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "palladium-business-hotel",
    name: "Palladium Business Hotel",
    category: "Gastronomia y hoteleria",
    area: "Buceo.",
    roles: "Hoteleria, gastronomia, recepcion y servicios.",
    applyUrl: "https://www.palladiumhotel.com.uy/es/se-parte-de-nuestro-equipo",
    applyEmail: "",
    sourceUrl: "https://www.palladiumhotel.com.uy/es/se-parte-de-nuestro-equipo",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "cafeteria-slow",
    name: "Cafeteria Slow",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Cafeteria, cocina y atencion.",
    applyUrl: "https://cafeteria.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://cafeteria.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "la-molienda",
    name: "La Molienda",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Ventas, atencion y cafeteria.",
    applyUrl: "https://www.lamolienda.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.lamolienda.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "lokotas",
    name: "Lokotas",
    category: "Gastronomia y hoteleria",
    area: "Montevideo.",
    roles: "Produccion, elaboracion y ventas.",
    applyUrl: "",
    applyEmail: "holatrabajo@lokotas.com.uy",
    sourceUrl: "https://lokotas.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "grupo-vierci-retail",
    name: "Grupo Vierci Retail",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, caja, reposicion y deposito.",
    applyUrl: "https://grupovierci.uy/empleo/",
    applyEmail: "",
    sourceUrl: "https://grupovierci.uy/empleo/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "tienda-inglesa",
    name: "Tienda Inglesa",
    category: "Comercio y atencion al cliente",
    area: "Montevideo y otras localidades.",
    roles: "Ventas, caja, reposicion, elaboracion, mantenimiento y deposito.",
    applyUrl: "https://app.genoma.work/jobs/tienda-inglesa",
    applyEmail: "",
    sourceUrl: "https://app.genoma.work/jobs/tienda-inglesa",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "grupo-disco-uruguay",
    name: "Grupo Disco Uruguay: Disco, Devoto, Devoto Express y Geant",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Caja, reposicion, atencion, deposito y elaboracion.",
    applyUrl: "https://institucional.disco.com.uy/shared//formempleo/form_empleo2018.php",
    applyEmail: "",
    sourceUrl: "https://institucional.disco.com.uy/shared//formempleo/form_empleo2018.php",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "macromercado",
    name: "Macromercado",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Caja, reposicion, deposito y atencion.",
    applyUrl: "https://www.macromercado.com.uy/empresa/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://www.macromercado.com.uy/empresa/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "market",
    name: "Market",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, atencion y deposito.",
    applyUrl: "https://www.market.com.uy/trabaja-con-nosotros",
    applyEmail: "busquedas@market.com.uy",
    sourceUrl: "https://www.market.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "stadium",
    name: "Stadium",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, caja, deposito y atencion.",
    applyUrl: "https://www.stadium.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.stadium.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "timeout",
    name: "Timeout",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, deposito, administracion, diseno y comercio electronico.",
    applyUrl: "https://www.timeout.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.timeout.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "el-clon",
    name: "El Clon",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Atencion, ventas, caja y deposito.",
    applyUrl: "https://www.elclon.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.elclon.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "pepe-ganga",
    name: "Pepe Ganga",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, caja, atencion y deposito.",
    applyUrl: "https://www.pepeganga.com.uy/trabaj%C3%A1-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.pepeganga.com.uy/trabaj%C3%A1-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "fivisa",
    name: "Fivisa",
    category: "Comercio y atencion al cliente",
    area: "Centro y otras sucursales.",
    roles: "Ventas, deposito, logistica y administracion.",
    applyUrl: "https://www.fivisa.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.fivisa.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "aldo",
    name: "Aldo",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, caja, atencion y deposito.",
    applyUrl: "https://aldo.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://aldo.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "loi",
    name: "LOi",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, atencion, logistica y comercio electronico.",
    applyUrl: "",
    applyEmail: "rrhh@loi.com.uy",
    sourceUrl: "https://loi.com.uy/contacto",
    verifiedAt: "2026-07-22",
    status: "Por revisar",
    active: true
  },
  {
    id: "redpagos",
    name: "Redpagos",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Caja, atencion al cliente y administracion.",
    applyUrl: "https://www.redpagos.com.uy/trabaja-con-nosotros-13",
    applyEmail: "",
    sourceUrl: "https://www.redpagos.com.uy/trabaja-con-nosotros-13",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "bookshop",
    name: "Bookshop",
    category: "Comercio y atencion al cliente",
    area: "Montevideo.",
    roles: "Ventas, caja, atencion y deposito.",
    applyUrl: "",
    applyEmail: "cvs@bookshop.com.uy",
    sourceUrl: "https://www.bookshop.com.uy/rrhh",
    verifiedAt: "2026-07-22",
    status: "Por revisar",
    active: true
  },
  {
    id: "prolesa",
    name: "Prolesa",
    category: "Comercio y atencion al cliente",
    area: "Centro y otras localidades.",
    roles: "Ventas, deposito, logistica y administracion.",
    applyUrl: "https://www.institucional.prolesa.com.uy/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.institucional.prolesa.com.uy/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "clean-in",
    name: "Clean In",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Limpieza y servicios generales.",
    applyUrl: "https://cleanin.com.uy/trabajo.html",
    applyEmail: "",
    sourceUrl: "https://cleanin.com.uy/trabajo.html",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "gss-facility-services",
    name: "GSS Facility Services",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Limpieza, seguridad y mantenimiento.",
    applyUrl: "https://gss.com.uy/",
    applyEmail: "",
    sourceUrl: "https://gss.com.uy/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "prosegur-uruguay",
    name: "Prosegur Uruguay",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Seguridad, logistica, vigilancia y atencion.",
    applyUrl: "https://www.prosegur.com.uy/conoce/trabaja-con-nosotros",
    applyEmail: "",
    sourceUrl: "https://www.prosegur.com.uy/conoce/trabaja-con-nosotros",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "divisol",
    name: "Divisol",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Limpieza, lavado de vehiculos, supervision y administracion.",
    applyUrl: "https://divisol.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://divisol.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "ralesur",
    name: "Ralesur",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Planta, deposito, produccion y logistica.",
    applyUrl: "https://ralesur.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://ralesur.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "malatic",
    name: "Malatic",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Distribucion, deposito, ventas y logistica.",
    applyUrl: "https://malatic.com/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://malatic.com/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Por revisar",
    active: true
  },
  {
    id: "clean-and-company",
    name: "Clean & Company",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Limpieza y servicios generales.",
    applyUrl: "https://www.cleanandcompany.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://www.cleanandcompany.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "abra",
    name: "ABRA",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo y otras localidades.",
    roles: "Limpieza, jardineria, cuidados, atencion y servicios.",
    applyUrl: "https://www.abralimpieza.com.uy/trabaja.html",
    applyEmail: "",
    sourceUrl: "https://www.abralimpieza.com.uy/trabaja.html",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "ues",
    name: "UES",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Correo, distribucion, deposito, reparto y logistica.",
    applyUrl: "https://www.ues.com.uy/llamados_laborales.html",
    applyEmail: "",
    sourceUrl: "https://www.ues.com.uy/llamados_laborales.html",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "murchison-uruguay",
    name: "Murchison Uruguay",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Operaciones portuarias, administracion y logistica.",
    applyUrl: "https://www.murchison.com.uy/es/envio-de-cv.html",
    applyEmail: "",
    sourceUrl: "https://www.murchison.com.uy/es/envio-de-cv.html",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "limpieza-capital",
    name: "Limpieza Capital",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Limpieza y mantenimiento.",
    applyUrl: "https://www.limpiezacapital.com/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://www.limpiezacapital.com/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "raisol",
    name: "Raisol",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Servicios, mantenimiento y operaciones.",
    applyUrl: "https://raisol.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://raisol.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "tr-transporte-logistica",
    name: "TR Transporte y Logistica",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Choferes, operaciones, mantenimiento y administracion.",
    applyUrl: "https://tr.com.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://tr.com.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "cleanmax",
    name: "Cleanmax",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo.",
    roles: "Limpieza, supervision y mantenimiento.",
    applyUrl: "https://cleanmax.uy/trabaja-con-nosotros/",
    applyEmail: "",
    sourceUrl: "https://cleanmax.uy/trabaja-con-nosotros/",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  },
  {
    id: "dac",
    name: "DAC",
    category: "Logistica, limpieza y servicios",
    area: "Montevideo y todo Uruguay.",
    roles: "Distribucion, agencias, deposito, reparto y logistica.",
    applyUrl: "https://www.dac.com.uy/trabaja",
    applyEmail: "",
    sourceUrl: "https://www.dac.com.uy/trabaja",
    verifiedAt: "2026-07-22",
    status: "Verificado",
    active: true
  }
];
